-- AlterTable
ALTER TABLE "Settings" ADD COLUMN     "appUrl" TEXT,
ADD COLUMN     "digestDayOfWeek" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "digestHour" INTEGER NOT NULL DEFAULT 9,
ADD COLUMN     "directorySyncHour" INTEGER NOT NULL DEFAULT 2,
ADD COLUMN     "ldapAccessGroupDn" TEXT,
ADD COLUMN     "ldapBaseDn" TEXT,
ADD COLUMN     "ldapBindDn" TEXT,
ADD COLUMN     "ldapBindMode" TEXT NOT NULL DEFAULT 'upn',
ADD COLUMN     "ldapBindPasswordEnc" TEXT,
ADD COLUMN     "ldapEnabled" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "ldapNestedGroups" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "ldapPersonFilter" TEXT NOT NULL DEFAULT '(objectCategory=person)',
ADD COLUMN     "ldapStartTls" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "ldapTimeoutMs" INTEGER NOT NULL DEFAULT 10000,
ADD COLUMN     "ldapTlsRejectUnauthorized" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "ldapUpnSuffix" TEXT,
ADD COLUMN     "ldapUrl" TEXT,
ADD COLUMN     "reminderDayOfWeek" INTEGER NOT NULL DEFAULT 5,
ADD COLUMN     "reminderHour" INTEGER NOT NULL DEFAULT 16,
ADD COLUMN     "rolloverHour" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "sessionHours" INTEGER NOT NULL DEFAULT 12,
ADD COLUMN     "smtpFrom" TEXT NOT NULL DEFAULT 'TimeKeeper <timekeeper@example.com>',
ADD COLUMN     "smtpHost" TEXT,
ADD COLUMN     "smtpPasswordEnc" TEXT,
ADD COLUMN     "smtpPort" INTEGER NOT NULL DEFAULT 587,
ADD COLUMN     "smtpSecure" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "smtpUser" TEXT;

-- AlterTable
ALTER TABLE "User" ADD COLUMN     "failedSignIns" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "lockedUntil" TIMESTAMP(3),
ADD COLUMN     "passwordHash" TEXT,
ADD COLUMN     "passwordSetAt" TIMESTAMP(3);
